$schema: https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json

no-bare-urls: false
no-inline-html: false
first-line-h1: false
line-length:
  code_blocks: false
  tables: false
no-duplicate-heading:
  siblings_only: true
no-blanks-blockquote: false
