line-length:
  code_blocks: false # caught by prettier
  tables: false
no-duplicate-heading:
  siblings_only: true
no-inline-html: false
no-bare-urls: false # bare urls are needed in Nunjucks templates
first-line-h1: false # h1's are replaced with title in front matter
