ignorePaths:
  [
    custom-words.txt,
    _config.yml,
    _config.next.yml,
    db.json,
    package.json,
    package-lock.json,
    source/_data,
  ]

import: ["@cspell/dict-ru_ru/cspell-ext.json"]

dictionaries: [custom-words, en-gb, python, cpp, data-science, softwareTerms]
dictionaryDefinitions:
  - name: custom-words
    path: custom-words.txt
